### ISSUE TITLE
no blocks when this extension is added

### ISSUE THREAD

**Issue by dsssssssss9** [bsiever/microbit-pxt-speech#1]
When i add this extension to the Editor although it shows up in explorer under Javascript, i don't see any blocks

have tried both the current & beta versions of Makecode editor 

What am i doing wrong?

**Comment by bsiever** [comment]
Hi @dsssssssss9  .  This is an incomplete extension --- It was a prototype that I started on but did not finish.   I didn't finish it because someone else already has a great working extension for SAM/speech.  Use : https://github.com/adamish/pxt-billy instead.

Thanks for posting.  I will remove this repo (or make it private) to avoid this sort of confusion.

**Comment by dsssssssss9** [comment]
Thanks for that ...

was just looking at the state of such extensions for Micro:Bit as i saw a question on the forums

No need to remove this repo i think ?
maybe someone will find inspiration from it ?

**Comment by dsssssssss9** [comment]
Thanks for that ...

was just looking at the state of such extensions for Micro:Bit as i saw a question on the forums

No need to remove this repo i think ?
maybe someone will find inspiration from it ?
